export const API_URL: string = 'https://api.themoviedb.org/3/search/movie?'
export const API_TRENDING_URL: string = 'https://api.themoviedb.org/3/trending/movie/day?language=en-US'
export const API_POPULAR_URL: string = 'https://api.themoviedb.org/3/movie/popular?language=en-US&page=1'
export const API_TOP_RATED_URL: string = 'https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1'
export const API_IMAGE_URL: string = 'https://image.tmdb.org/t/p/w200'
export const API_IMAGE_MAIN_URL: string = 'https://image.tmdb.org/t/p/w300'
export const API_IMAGE_HERO_URL: string = 'https://image.tmdb.org/t/p/w500'
